### DISCUSSION TITLE
Deployment with docker - posgresql issue

### DISCUSSION THREAD

**Discussion by t-lie** [fonoster/routr#295] [Q&A] [answered]
Hi,
I just found this project and tried to deploy it with given sample compose file.
But it seems there is any psgres DB needed.
If try to start the container it shows:
`Creating network "routr_default" with the default driver
Creating routr_routr_1 ... done
Attaching to routr_routr_1
routr_1  | [INFO  tini (1)] Spawned child process '/bin/sh' with pid '7'
routr_1  | pg_ctl: directory "/var/lib/postgresql/data" is not a database cluster directory
routr_1  | [INFO  tini (1)] Main child exited normally (with status '1')
routr_routr_1 exited with code 1
`

Can anyone help me getting it running? Because there was no information about needed additional container with posgres, I didn't deploy one...

Thanks

**Comment by psanders** [comment]
Could you share the mentioned compose files?

**Reply by HamzaMaazaoui** [reply]
I have the same problem, here is my compose file 


```
[INFO  tini (1)] Spawned child process '/bin/sh' with pid '7'
pg_ctl: directory "/var/lib/postgresql/data" is not a database cluster directory
[INFO  tini (1)] Main child exited normally (with status '1')
```

```
version: "3"

services:
  routr:
    image: fonoster/routr-one:latest
    environment:
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
    ports:
      - 51908:51908
      - 5060:5060/udp
    volumes:
      - shared:/var/lib/postgresql/data

volumes:
  shared:
```
