### ISSUE TITLE
Help with Gateway

### ISSUE THREAD

**Issue by baerni** [fonoster/routr#143]
Hi. I need help setting up my gateway. I have a number with a VoIP provider. I entered all the data, unfortunately the gateway does not work when I try to call an external number via Routr.
This is my configuration:
domains.yml file:
```
- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: SIP Server
  spec:
    context:
      domainUri: sip.my.domain
      egressPolicy:
        rule: .{5,} 
        numberRef: dd76afc94b
```

gateways.yml file:
```
- apiVersion: v1beta1
  kind: Gateway
  metadata:
    ref: gw50a1a4ca
    name: my.provider
  spec:
    host: sip.my.provider
    port: 5060
    transport: udp
    credentials:
      username: 'xxxxxxxxx'
      secret: 'xxxxxxxxx'
```

numbers.yml file:
```
- apiVersion: v1beta1
  kind: Number
  metadata:
    ref: dd76afc94b
    gwRef: gw50a1a4ca
    geoInfo:                
      countryISOCode: PL
  spec:
    location:
      telUrl: 'tel:xxxxxxxxx'
      aorLink: 'sip:1001@sip.my.domain'
```
