### ISSUE TITLE
Issue mounting volumes with docker-compose.yaml

### ISSUE THREAD

**Issue by Bonanzameh** [fonoster/routr#162]
Hello,

I'm having issues with mounting a persistent volume for configuration purposes.
The compose yaml looks like this; 
```yaml
  routr:
    image: fonoster/routr
    container_name: routr
    ports:
      - 4567:4567
      - 5060:5060
      - 5060:5060/udp
      - 5061:5061
      - 5062:5062
      - 5063:5063
    environment:
      - TZ=Europe/Brussels
    restart: unless-stopped
    volumes: 
      - /opt/routr/config:/opt/routr/config
```

and results in this error:
ERROR StatusLogger File not found in file system or classpath: config/log4j2.yml
ERROR StatusLogger Reconfiguration failed: No configuration found for '67424e82' at 'null' in 'null'

Changing the (container) volume to anything else will allow the contaire to spin up fine, though without access to the config files from the host mount. 

Having all files manually copied and pasted in the opt/routr/config dir on the host yields the following error:
`15:31:39.999 [main] ERROR io.routr.core.Launcher - Unable to open configuration file
[INFO  tini (1)] Spawned child process './routr' with pid '7'
[INFO  tini (1)] Main child exited normally (with status `'0')`
This location is drwxrwxrwx including subdirs. and explicitely so for the log4j2.yml file.

I tried manual compose file; manual installations too. 

Docker version 20.10.22, build 3a2c30b
Docker Compose version v2.14.1
On Ubuntu 22.04.1 LTS

I'm sure i'm missing something silly but I can't seem to figure it out on my own. Can you please help? 

thanks.
