### ISSUE TITLE
Connect crashes on 2nd REGISTER attempt after 401

### ISSUE THREAD

**Issue by philjones88** [fonoster/routr#239]
**Describe the bug**

SIPjs sends a REGISTER without the authorization values, received a 401 from the SIP Server (CUCM) and sends another REGISTER with the authorization values set.

This causes routr connect to crash it seems:

```
[INFO  tini (1)] Spawned child process 'run' with pid '7'
2023-11-02 17:34:49.499 [verbose]: (grpc-health-check) /usr/local/lib/node_modules/@routr/connect/node_modules/@fonoster/grpc-health-check/dist/add-health-to-server.js added healthcheck service {}
2023-11-02 17:34:49.522 [info]: (common) /usr/local/lib/node_modules/@routr/connect/node_modules/@routr/common/dist/service.js starting routr service {"name":"connect","bindAddr":"0.0.0.0:51904"}
2023-11-02 17:35:11.313 [verbose]: (connect) /usr/local/lib/node_modules/@routr/connect/dist/service.js connect processor received new request {"ref":"g8bemgv0sa4pkvtdqcf5","method":"REGISTER","type":"(request)","edgePort":"498503b12412"}
2023-11-02 17:35:11.605 [verbose]: (connect) /usr/local/lib/node_modules/@routr/connect/dist/service.js connect processor received new request {"ref":"g8bemgv0sa4pkvtdqcf5","method":"REGISTER","type":"(request)","edgePort":"498503b12412"}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 5 NOT_FOUND: resource not found:
    at callErrorFromStatus (/usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/usr/local/lib/node_modules/@routr/connect/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /usr/local/lib/node_modules/@routr/connect/node_modules/@opentelemetry/instrumentation-grpc/build/src/grpc-js/clientUtils.js:92:31
    at /usr/local/lib/node_modules/@routr/connect/node_modules/@opentelemetry/instrumentation-grpc/build/src/grpc-js/index.js:152:170
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at AsyncLocalStorageContextManager.with (/usr/local/lib/node_modules/@routr/connect/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ContextAPI.with (/usr/local/lib/node_modules/@routr/connect/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at ServiceClientImpl.clientMethodTrace [as findBy] (/usr/local/lib/node_modules/@routr/connect/node_modules/@opentelemetry/instrumentation-grpc/build/src/grpc-js/index.js:152:42)
    at /usr/local/lib/node_modules/@routr/connect/node_modules/@routr/common/dist/connect/api/client.js:143:20
    at new Promise (<anonymous>) {
  code: 5,
  details: 'resource not found: ',
  metadata: Metadata {
    internalRepr: Map(2) {
      'content-type' => [ 'application/grpc+proto' ],
      'date' => [ 'Tue, 14 Nov 2023 17:35:11 GMT' ]
    },
    options: {}
  }
}

Node.js v18.18.2
[INFO  tini (1)] Main child exited normally (with status '1')
```

It sends these SIP messages (from SIPjs, using SimpleUser for prototyping):
(some internal names/values redacted)
```
REGISTER sip:cucm.lab SIP/2.0
Via: SIP/2.0/WSS cvfo7gtfpv86.invalid;branch=z9hG4bK5980864
To: <sip:7070@cucm.lab>
From: "Prototype" <sip:7070@cucm.lab>;tag=ub04e1ao3c
CSeq: 2 REGISTER
Call-ID: g8bemgv0sa4pkvtdqcf5
Max-Forwards: 70
Contact: <sip:7070@cvfo7gtfpv86.invalid;transport=ws>;expires=3600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound, path, gruu
User-Agent: SIP.js/0.21.1
Content-Length: 0


SIP/2.0 401 Unauthorized
CSeq: 2 REGISTER
Call-ID: g8bemgv0sa4pkvtdqcf5
From: "Prototype" <sip:7070@cucm.lab>;tag=ub04e1ao3c
To: <sip:7070@cucm.lab>
Via: SIP/2.0/WSS cvfo7gtfpv86.invalid;branch=z9hG4bK5980864;received=192.168.65.1;rport=37674
WWW-Authenticate: Digest realm="cucm.lab",domain="",nonce="82e95101534b9333171fbc81f8da93e8",algorithm=MD5,qop="auth",opaque=""
Content-Length: 0


REGISTER sip:cucm.lab SIP/2.0
Via: SIP/2.0/WSS cvfo7gtfpv86.invalid;branch=z9hG4bK4936193
To: <sip:7070@cucm.lab>
From: "Prototype" <sip:7070@cucm.lab>;tag=ub04e1ao3c
CSeq: 3 REGISTER
Call-ID: g8bemgv0sa4pkvtdqcf5
Max-Forwards: 70
Authorization: Digest algorithm=MD5, username="7070@cucm.lab", realm="cucm.lab", nonce="...", uri="sip:cucm.lab", response="...", qop=auth, cnonce="...", nc=00000001
Contact: <sip:7070@cvfo7gtfpv86.invalid;transport=ws>;expires=3600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: outbound, path, gruu
User-Agent: SIP.js/0.21.1
Content-Length: 0
```

**To Reproduce**

Using this compose file:

```
version: "3"

services:
  edgeport:
    container_name: edgeport
    image: fonoster/routr-edgeport:latest
    platform: linux/amd64
    environment:
      LOGS_LEVEL: verbose
    ports:
      - 5070:5060
      - 5070:5060/udp
      - 5071:5061
      - 5072:5062
      - 5073:5063
    volumes:
      - ./config/edgeport.yaml:/etc/routr/edgeport.yaml
      - ./certs/ca.crt:/etc/routr/certs/ca.crt
      - ./certs/server.crt:/etc/routr/certs/server.crt
      - ./certs/server.key:/etc/routr/certs/server.key
    networks:
      internal:

  dispatcher:
    container_name: dispatcher
    image: fonoster/routr-dispatcher:latest
    platform: linux/amd64
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51901
    volumes:
      - ./config/dispatcher.yaml:/etc/routr/dispatcher.yaml
    networks:
      internal:

  connect:
    container_name: connect
    image: fonoster/routr-connect:latest
    platform: linux/amd64
    environment:
      LOGS_LEVEL: verbose
      LOCATION_ADDR: location:51902
      API_ADDR: apiserver:51907
    expose:
      - 51904
    networks:
      internal:

  location:
    container_name: location
    image: fonoster/routr-location:latest
    platform: linux/amd64
    build: ./mods/location
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51902
    volumes:
      - ./config/location.yaml:/etc/routr/location.yaml
    networks:
      internal:

  rtprelay:
    container_name: rtprelay
    image: fonoster/routr-rtprelay:latest
    platform: linux/amd64
    environment:
      LOGS_LEVEL: verbose
      RTPENGINE_HOST: rtpengine
    expose:
      - 51903
    networks:
      internal:

  apiserver:
    container_name: apiserver
    image: fonoster/routr-simpledata:latest
    platform: linux/amd64
    environment:
      LOGS_LEVEL: verbose
    expose:
      - 51907
    volumes:
      - ./resources:/etc/routr/resources
    networks:
      internal:

  rtpengine:
    image: fonoster/rtpengine:latest
    platform: linux/amd64
    environment:
      PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      LOG_LEVEL: 6
      BIND_NG_PORT: 22222
      PORT_MIN: 31000
      PORT_MAX: 32000
    ports:
      - 22222:22222/udp
    expose:
      - 31000:32000/udp

volumes:
  shared:

networks:
  internal:
    driver: bridge
```

A single Peer and Truck to the SIP server (CUCM):

peers.yaml

```
- apiVersion: v2beta1
  kind: Peer
  ref: cucm-peer
  metadata:
    name: CUCM-Peer
  spec:
    aor: cucm.lab
    username: cucm
    loadBalancing:
      withSessionAffinity: true
      algorithm: round-robin
    enabled: true
```

trunks.yaml

```
- apiVersion: v2beta1
  kind: Trunk
  ref: cucm-trunk
  metadata:
    name: CUCM-Trunk
  spec:
    inbound:
      uri: local.lab
    outbound:
      sendRegister: true
      uris:
        - uri:
            host: cucm.lab
            port: 5060
            transport: udp
          priority: 1
          weight: 1
          enabled: true
```

**Expected behavior**

Should handle 2nd REGISTER

**Screenshots**

**System information (please complete the following):**
 - OS: [e.g. Linux]
 - NodeJS, NPM versions [e.g. v14.16.0, 7.10.0]
 - CTL version [e.g. 0.1 ]

**Additional context**
