### ISSUE TITLE
[FEATURE]: Add support for secure transport for trunking

### ISSUE THREAD

**Issue by psanders** [fonoster/routr#256]
### Is your feature request related to a problem?

We currently support secure transport for inbound requests. However, as the Requester service doesn’t support secure transport, we are unable to provide secure transport for trunking. Adding secure transport for trunking is essential to improve the security of Routr.

### Describe the solution you'd like

A solution would allow us to use secure transport while defining URIs for trunk spec. For example, the following trunking configuration would enable connecting to a trunk provider with TLS:

```yaml

- apiVersion: v2beta1
  kind: Trunk
  ref: trunk-01
  metadata:
    name: Test Trunk
    region: us-west1
  spec:
    outbound:
      credentialsRef: credentials-01
      uris:
        - uri:
            user: pbx-1
            host: sip.provider.net
            port: 5061
            transport: tls
          priority: 10
          weight: 10
          enabled: true
```

### Describe alternatives you've considered

One option is to take no action, given the limited traction this issue has received.

### Additional context

N/A
