### ISSUE TITLE
[FEATURE]: Request for Providing Support Documentation on Call Routing

### ISSUE THREAD

**Issue by soumyaicv** [fonoster/routr#275]
### Is your feature request related to a problem?

I am facing difficulties due to the lack of documentation on Call Routing:

### Describe the solution you'd like

I have been exploring Routr for our SIP infrastructure needs and have found it very promising. However, I am facing difficulties due to the lack of documentation on Call Routing: There doesn't seem to be any detailed documentation or examples on how to configure and manage call routing in Routr. Could you please provide comprehensive documentation or guides on this feature?

**Comment by psanders** [comment]
Could you describe what you are trying to do? 

Also, would you describe what you have tried?

**Comment by soumyaicv** [comment]
Thank you for your response, and here is a detailed explanation of what I'm trying to achieve and the progress I've made so far.

What I'm Trying to Do:

I want to implement both parallel and sequential calling using Routr SIP service.

1. **Parallel Calling**:
   - The call should be sent to multiple agents (Agent 1, Agent 2, Agent 3) simultaneously.
   - Once the call is answered by one agent, the calls to the other agents should be canceled.

2. **Sequential Calling**:
   - The call should first be sent to Agent 1.
   - If Agent 1 does not answer, the call should be sent to Agent 2.
   - If Agent 2 also does not answer, the call should then be sent to Agent 3.

What I Have Tried:

I have followed the [Running Routr and RTPEngine with Docker Compose](https://github.com/fonoster/routr) tutorial to set up Routr and RTPEngine. Here are the steps I have taken:

1. Set Up Docker Compose:
   I created a `compose.yml` file to run both Routr and RTPEngine services.

   ```yaml
   version: "3"

   services:
     routr:
       image: fonoster/routr-one:latest
       environment:
         EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
         RTPENGINE_HOST: rtpengine
       ports:
         - 51908:51908
         - 5062:5062
         - 5060:5060
       volumes:
         # Ensures the data survives container restarts
         - shared:/var/lib/postgresql/data

     rtpengine:
       image: fonoster/rtpengine:latest
       environment:
         PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
         PORT_MIN: 10000
         PORT_MAX: 10100
         LOG_LEVEL: 6
       ports:
         - 22222:22222/udp
         - 10000-10100:10000-10100/udp

   volumes:
     shared:
   ```

   I then ran the following command to start the services:

  
   DOCKER_HOST_ADDRESS=192.168.1.7 docker compose up
 

2. Configured a Domain and Agents:
   Using Routr's command-line tool, I created a domain and agents.

  
   rctl domains create --insecure


   Created credentials 

 
   rctl credentials create --insecure


   Created agents :

  
   rctl agents create --insecure

I am looking for comprehensive documentation, examples, or guidance on how to achieve this with Routr.

Any help or pointers towards achieving this setup would be greatly appreciated. Thank you for your support!
