### ISSUE TITLE
Failed to start Postgres while running Routr One

### ISSUE THREAD

**Issue by psanders** [fonoster/routr#296]
### Discussed in https://github.com/fonoster/routr/discussions/295

<div type='discussions-op-text'>

<sup>Originally posted by **t-lie** October 16, 2024</sup>
Hi,
I just found this project and tried to deploy it with given sample compose file.
But it seems there is any psgres DB needed.
If try to start the container it shows:
`Creating network "routr_default" with the default driver
Creating routr_routr_1 ... done
Attaching to routr_routr_1
routr_1  | [INFO  tini (1)] Spawned child process '/bin/sh' with pid '7'
routr_1  | pg_ctl: directory "/var/lib/postgresql/data" is not a database cluster directory
routr_1  | [INFO  tini (1)] Main child exited normally (with status '1')
routr_routr_1 exited with code 1
`

Can anyone help me getting it running? Because there was no information about needed additional container with posgres, I didn't deploy one...

Thanks</div>

**Comment by psanders** [comment]
**Added context from Discod Discussion:**

I'm getting the same issue as specified in this github issue ⁠🟩⏐github⁠
pg_ctl: directory "/var/lib/postgresql/data" is not a database cluster directory
I'm using the compose yaml specified here: https://routr.io/docs/2.11.5/overview/deploy-with-docker#deploying-routr

which is the same as the github repository readme. It looks like:

```
version: "3"

services:
  routr:
    image: fonoster/routr-one:latest
    environment:
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
    ports:
      - 51908:51908
      - 5060:5060/udp
    volumes:
      - shared:/var/lib/postgresql/data

volumes:
  shared:
```

I've also tried changing binding instead of a volume with /opt/docker/sip/:/var/lib/postgresql/data as well as giving the volume a different name to make it look nicer within dockge like

```
volumes:
  shared:
    name: routr-postgres-data
```

I did a quick check, and there was a change to make the postgres database optional ~4 months ago. And the compose.yaml file in the root of the repository is substantially more complicated than the suggested deployment compose yaml. Which apparently hasn't changed since at least December.

Is there updated documentation on how to do a fresh deployment via Docker for testing? Is there any documentation on the images, ports and environment variables used in the compose.yaml file? (https://github.com/fonoster/routr/blob/main/compose.yaml)

Thanks for your time.

![image](https://github.com/user-attachments/assets/23a22af5-5509-4a4c-8b2b-5cca140d36e2)
