### ISSUE TITLE
Use routr for a close group

### ISSUE THREAD

**Issue by plague-doctor** [fonoster/routr#48]
Guys, I am so happy I have found your project that I cannot express in words. :clap: 
I just need some hand-holding and maybe a help with config files, etc.
We have a close group of users (6 people) and we would like to be able to communicate using VoIP. We do not need conference calls or calls outside of the group. We have a mixture of VoIP devices ranges from SoftPhones (LinPhone, CSIPSimple) to Yealink VoIP devices.
I would like to host routr.io on my Docker server. 
Can you guys give me some suggestions on how to configure routr to cater to what we are looking for? What ports should I open on the firewall? Any help would be highly appreciated.

**Comment by psanders** [comment]
For your specific use case, I recommend looking into the [docker/compose guide](https://routr.io/docs/guides/running-with-docker-or-compose) and [basic-setup guide](https://routr.io/docs/guides/basic-setup). Those two guides will help you run Routr in your local network using Docker.

The next challenge is making Routr available outside of your network. Since you are running the service behind a NAT you will need to tell Routr to [use your outside-facing IP](https://routr.io/docs/configuration/general/#configuring-the-server-behind-a-nat). Also, You can use port `5060` unless is blocked by your ISP.

Finally, I recommend looking into a service like [no-ip](https://www.noip.com/) to make your setup more user friendly.

**Comment by plague-doctor** [comment]
Thank you very much for your prompt reply, @psanders. I have configured my setup according to your suggestions, but few problems came up:

My config files look like this:
```
--------------------------------------------------------------- config.yml 
apiVersion: v1beta1
spec:
  externAddr: 203.xxx.xxx.xxx
  localnets: [192.168.1.0/24,192.168.10.0/24]

  transport:
    - protocol: udp
      port: 5060
    - protocol: tcp
      port: 5060
    - protocol: tls
      port: 5061
```
```
--------------------------------------------------------------- domains.yml
- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: My SIP Server
  spec:
    context:
      domainUri: sip.my-domain.net
```
```
--------------------------------------------------------------- gateways.yml
- apiVersion: v1beta1
  kind: Gateway
  metadata:
    name: SIP-PROVIDER
    ref: GW01
  spec:
    host: my-sip-provider.com
    transport: tls
    credentials:
      username: 'username'
      secret: password
```
```
--------------------------------------------------------------- numbers.yml
- apiVersion: v1beta1
  kind: Number
  metadata:
    gwRef: GW01
    geoInfo:
      city: My-City
      country: My-Country
      countryISOCode: My-Country-Code
  spec:
    location:
      telUrl: 'tel:0000000000'
      aorLink: 'sip:1001@sip.my-domain.net'
```
```
--------------------------------------------------------------- agents.yml
- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Yealink
  spec:
    credentials:
      username: '1000'
      secret: '12345'
    domains: [sip.my-domain.net]

- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Mobile
  spec:
    credentials:
      username: '1001'
      secret: '12345'
    domains: [sip.my-domain.net]
```
```
--------------------------------------------------------------- peers.yml
- apiVersion: v1beta1
  kind: Peer
  metadata:
    name: Asterisk PBX
  spec:
    credentials:
      username: ast
      secret: '1234'
```
```
--------------------------------------------------------------- users.yml
- apiVersion: v1beta1
  kind: User
  metadata:
    name: Admin
  spec:
    credentials:
      username: 'admin'
      secret: 'changeit'
```

Router configuration:
- Ports Forwarded from WAN to Docker server: 5060, 5061, 5062, 5063, 4567 (TCP and UDP)

### Case 1: Using `1.0.0-rc3` release:
- Both my devices can successfully register with routr server (over TCP or TLS. UDP doesn't work). 
- When trying to call, I get this error:
`
[ERROR] TypeError: v.includes is not a function
`

### Case 2: Using previous `1.0.0-rc2` release:
- Both my devices can successfully register with routr server (over TCP or TLS. UDP doesn't work).
  - When both devices are in LAN (either 192.168.1.0/24 or 192.168.10.0/24) the connection is established and VoIP works fine. :+1:
  - When mobile uses `Mobile Network` I still can register with routr server, but I cannot establish any calls:
    - calling from Yealink (LAN) to outside: Mobile rings, cannot hear anything.
    - calling from Mobile (Outside) to Yealink (LAN):  No connection at all, error thrown:
`
[ERROR] javax.sip.TransactionUnavailableException: Could not resolve next hop or listening point unavailable!
`

#### Questions:
1. Please help with the configuration, so I can use external devices (mobiles, other group members devices).
2. Is there a problem with latest 1.0.0-rc3 release? `[ERROR] TypeError: v.includes is not a function` ?
3. In my use case I do not need to use any gateway. However I still need to provide files `gateways.yml`, `numbers.yml`... Routr fails without those files... Is there a way to ignore this requirement? 
4. I do not have any Asterisk PBX. Do I still need to provide `peers.yml` configuration? How to disable it?
