### ISSUE TITLE
Could not create a message channel

### ISSUE THREAD

**Issue by besworks** [fonoster/routr#66]
I've been trying to set up a private web-based phone system for a small team using routr and [ctxSip](https://github.com/collecttix/ctxSip). The server I'm setting this up on is accessible over the internet with a FQDN and the web interface itself is behind a basic http auth security wall. For the proof of concept I have set up two separate instances of the ctxSip client. I can get both clients registered to the routr server over wss:// and even have them call each other but I'm only getting audio in one direction and the call ends automatically after 30 seconds (the end which can't hear anything disconnects). The error messages I get in the log are as follows:

```
[ERROR] javax.sip.SipException: Could not create a message channel for f6281uric6b1.invalid:5060/ws
[ERROR] ^^^ ** LINE ABOVE REPEATED MULTIPLE TIMES ** ^^^
[WARN ] Unable to connect to host -> `mbk5uskco486.invalid`.(Verify your network status)
[WARN ] Unable to connect to host -> `f6281uric6b1.invalid`.(Verify your network status)
```

The strange thing about the error above is that the port number and protocol do not match what I have set up in my config.yml. I do have both TCP & UDP protocols enabled on port 5060 but I do not have the WS protocol enabled at all and WSS is actually running on port 5065. I'm not sure what significance that has on this issue or what I could be doing wrong... Any help figuring this out would be appreciated.

**Comment by psanders** [comment]
I'm currently looking into this issue. Can you send me the content of your config.yml? Audio/disconnection issues are typically related to NAT problems.

**Comment by besworks** [comment]
I thought it seemed like a NAT issue as well but that shouldn't be the case with wss:// right? I use websockets for my own web development projects and have never experienced any NAT issues with them. The ports are wide open on the server side. It shouldn't matter what the client side network topology is like. Each instance of the web client should be making a direct connection to the socket and bypassing any local routing. Hence my confusion...

Here's my config.yml (with the password fields masked). The certificate used for the wss:// connection is the same one that I use for https:// on my domain and is issued by Lets Encrypt.

```
apiVersion: v1beta1
spec:
  recordRoute: true
  securityContext:
    keyStore: etc/certs/domains-cert.jks
    trustStore: etc/certs/domains-cert.jks
    keyStorePassword: '********'
    trustStorePassword: '********'
    keyStoreType: 'jks'
    debugging: false
  transport:
    - protocol: udp
      port: 5060
    - protocol: tcp
      port: 5060
    - protocol: wss
      port: 5065
```

Thanks for looking into this for me.
