### ISSUE TITLE
Support ephemeral auth

### ISSUE THREAD

**Issue by mbrodala** [fonoster/routr#77]
I think it would be useful if Routr did support ephemeral authentication. The basic idea behind this is that an application could be built with a service which generates user credentials using a secret. This secret is then shared with other services which need to validate these credentials.

In Kamailio this works using the [auth_ephemeral](https://kamailio.org/docs/modules/5.3.x/modules/auth_ephemeral.html) module.

The benefit of this is that one does not need to create users in SIP servers for authentication.

What do you think?

**Comment by psanders** [comment]
That sounds like a good feature proposal. I believe it is doable and especially useful for WebRTC. My initial thought is to create a spec, at the Domain level, that enables ephemeral authentication. It could be something like:

```yaml
...
spec:
  ephemeralCredentials:
    enabled: true
    privateKey: /path/to/private/key
```

The rest endpoint request/response could be something like this:

```bash
GET /api/{apiversion}/agent/ephemeral
{
   "domain": "sip.local",
   "username": "john",
   "expires": 3600
}

HTTP/1.1 200 OK
{
  "status": 200,
  "message": "Successful request",
  "data": {
    "username": "john"
    "secret": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.TZZ4kp5xIdYzs5RRt6_qVxJcOiLdk1IEHFMBSZ7SRENx6kyVhwfAlm-oeM4L2XFIr4evlTCxKEIKc0fZKwPcjw"
    "expires": 3600
  }
}
```

It doesn't look like colossal development. If we go forward with this feature, we could include in Routr RC5  but only as an experimental feature since we are freezing the public APIs.

**Comment by mbrodala** [comment]
Thanks for the quick response. :-)

The setup described here would make Routr the service which provides credentials, thus a producer. However, it would be better if Routr was simply one of many consumers and thus offer an option to inject a credential secret (environment variable, spec, etc.)

Then Routr could use this to verify incoming credentials just like the other consumers.

What do you think?

**Comment by psanders** [comment]
I have been thinking about a few options to implement this. The one that resonates the most with me is to accept the fields `created` and `expires` in the credentials spec for Agents(and potentially for Peers too). To summarize, we could have the endpoint `/api/{apiversion}/agent/{ref}/credentials` that accepts a PUT/POST method and a body as follows:

```yaml
{
   "username": "john",
   "secret": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.TZZ4kp5xIdYzs5RRt6_qVxJcOiLdk1IEHFMBSZ7SRENx6kyVhwfAlm-oeM4L2XFIr4evlTCxKEIKc0fZKwPcjw"
   "expires": 3600
}
```

This will alter an Agent's state to look like this:

```yaml
{
  "apiVersion": "v1beta1",
  "kind": "Agent",
  "metadata": {
    "name": "John Doe"
  },
  "spec": {
    "credentials": {
      "expires": 3600,
      "created": "2020-05-01T15:12:34.000Z",
      "username": "john",
      "secret": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.TZZ4kp5xIdYzs5RRt6_qVxJcOiLdk1IEHFMBSZ7SRENx6kyVhwfAlm-oeM4L2XFIr4evlTCxKEIKc0fZKwPcjw"
    },
    "domains": [
      "sip.local"
    ]
  }
}
```

From there, it will reasonably easy to validate the credentials during the registration process. 

What do you think?
