### ISSUE TITLE
Invalid indentation in config.yml causes generic error.

### ISSUE THREAD

**Issue by envy** [fonoster/routr#93]
I had an indentation error in my config.yml:

```yaml
apiVersion: v1beta1
spec:
    bindAddr: '::'      # error here
  transport:
    - protocol: tcp
      port: 5060
    - protocol: udp
      port: 5060
```

This caused a generic "[ERROR] Unable to open configuration file" error that probably originates here: https://github.com/fonoster/routr/blob/master/mod/core/config/config_from_file.js

It would be nice if the actual execption is also printed such that uses know why it fails as the error currently could mean everything from "file not found" over "no permissions" to "error parsing yaml".
